version: "3.9"
services:
  admin-system-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: admin-system-dev
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    command: mvn spring-boot:run
