version: "3.9"

services:
  admin-system-dev:
    image: maven:3.9.6-eclipse-temurin-21
    container_name: admin-system-dev
    working_dir: /app
    volumes:
      - .:/app # Mount your project code
      - ~/.m2:/root/.m2 # Share your Maven cache (faster builds)
    ports:
      - "8080:8080" # Expose Spring Boot port
    command: mvn spring-boot:run
