FROM maven:3.9.6-eclipse-temurin-21
WORKDIR /app

# Preload dependencies
COPY pom.xml .
RUN mvn dependency:go-offline

# Copy source (will be overridden by volume)
COPY . .

EXPOSE 8080

CMD ["mvn", "spring-boot:run"]
